remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false

title: MrStickyPiston
description: I am a programmer and a fanatic minecraft player.

github:
  is_project_page: false

plugins:
- jekyll-remote-theme
